### ISSUE TITLE
我 部署iotex项目步骤中，执行 make fmt;make build;成功之后，执行make test 和make run 出现如下错误

### ISSUE THREAD

**Issue by chenshouzhang** [iotexproject/iotex-core#10] opened 2018-06-27 06:54 UTC
make test
go fmt ./...
makego test -short ./...
blockdb/blockdb.go:13:2: cannot find package "github.com/golang/glog" in any of:
	/home/chensc/go/src/github.com/iotexproject/iotex-core/vendor/github.com/golang/glog (vendor tree)
	/home/chensc/go/go/src/github.com/golang/glog (from $GOROOT)
	/home/chensc/go/src/github.com/golang/glog (from $GOPATH)
	/opt/go/src/github.com/golang/glog
Makefile:70: recipe for target 'test' failed
make: *** [test] Error 1

make run
go build -o ./bin/server -v ./server
export LD_LIBRARY_PATH=D_LIBRARY_PATH:/home/chensc/go/src/github.com/iotexproject/iotex-core/crypto/lib
./bin/server -config=e2etest/config_local_delegate.yaml -log-level=debug
./bin/server: error while loading shared libraries: libsect283k1_ubuntu.so: cannot open shared object file: No such file or directory
Makefile:129: recipe for target 'run' failed
make: *** [run] Error 127

**Comment by FishMeat** [comment] 2018-06-27 06:56
#9 same problem

**Comment by zjshen14** [comment] 2018-06-27 17:05
Which os are you on?

**Comment by Zhen-iotex** [comment] 2018-06-27 17:14
Did you run glide install inside iotex-core? You have to run this to install packages.

**Comment by zjshen14** [comment] 2018-06-29 02:13
> 复制 home/chensc/go/src/github.com/iotexproject/iotex-core/crypto/lib/libsect283k1_ubuntu.so到/usr/lib下 再 make run

Ideally, it's not necessary, because we set your `LD_LIBRARY_PATH` in the makefile script to where the crypto library stays. In which OS did you reproduce the issue?

The aforementioned logs seems to indicate `LD_LIBRARY_PATH` is not properly generated. Maybe this is the problem

> export LD_LIBRARY_PATH=D_LIBRARY_PATH:/home/chensc/go/src/github.com/iotexproject/iotex-core/crypto/lib

**Comment by zjshen14** [comment] 2018-07-17 22:12
Close the issue. Please feel free to reopen it if you could still reproduce the issue

**Closed by zjshen14** 2018-07-17 22:12 UTC
