### ISSUE TITLE
ioctl crashes in Ubuntu when creating an action 

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-core#2573] opened 2021-02-23 14:57 UTC
### What version of iotex-core are you using (`ioctl version`)?
Applies to ioctl v1.1.2 and v1.1.3 (v1.1.1 works well)

### What operating system and processor architecture are you using?
Linux Ubuntu amd64 20.04

### What did you do? If possible, provide a recipe for reproducing the error.
`ioctl contract deploy BYTECODE -s signerAccount`
or
`ioctl action transfer recipientAccount 10 -s signerAccount`

### What did you expect to see?
Usual action signature interaction with ioctl and final action hash 

### What did you see instead?
Segmentation fault: see attached log

[log.txt](https://github.com/iotexproject/iotex-core/files/6029673/log.txt)

**Comment by millken** [comment] 2021-02-24 02:26
Sorry, I can't reproduce the issue you're having,no problems found. does this happen by accident?

**Comment by dustinxie** [comment] 2021-02-24 03:55
cannot repro on Ubuntu 16.04 as well
ioctl: v1.1.3
go1.14.10
linux/adm64

**Comment by simonerom** [comment] 2021-02-24 11:03
> Sorry, I can't reproduce the issue you're having,no problems found. does this happen by accident?

This was a issue that Unify team faced when trying to integrate their platform into IoTeX: they were not able to reply their contracts after trying on 3 Linux machines. Therefore Zhi deployed for them (he used MacOS).

so I tried to reproduce to see if it’s an ioctl issue: this is what I did

- installed a fresh Ubuntu 20.04 in a Virtual machine, 
- installed ioctl with curl, 
- tried to deploy the Unify bytecode
- This gave me the same issue as the one they were experiencing.
- Then I tried to transfer tokens (same issue)
- Then I downgraded to ioctl 1.1.2 (same issue)
- Then I downgraded to 1.1.1 and the issue was not happening anymore

**Comment by dustinxie** [comment] 2021-02-24 21:14
another debug datapoint:
i verified building ioctl on ubuntu 20.04 with go1.14.6, it works fine, so the issue appears to happen when running the linux-amd64 ioctl binary (in github release) on ubuntu 20.04.
i think it is the difference of the specific Linux OS github used to build the binary (i am yet to find out which specific Linux) between ubuntu 20.04 that is causing the panic.

**Comment by millken** [comment] 2021-02-25 03:13
@dustinxie Before running, `export https_proxy=x.x.x.x:xx` and it should be works.

**Comment by millken** [comment] 2021-02-26 03:21
compile bug, fixed in https://github.com/iotexproject/iotex-core/pull/2574

**Closed** 2021-03-02 01:46 UTC
Labels: bug, ioctl
