### ISSUE TITLE
testnet fullsync glitch at block 5020517

### ISSUE THREAD

**Issue by dustinxie** [iotexproject/iotex-core#3648] opened 2022-09-26 16:36 UTC
### What would you like to be added
during testnet fullsync, it will first fail at block 5020517
```
2022-09-26T02:51:07.083Z	ERROR	factory/statedb.go:335	Failed to update state.	{"ioAddr": "io1amm3fxmwna3te40fcrvwqe8he05fzeqaxhjlys", "error": "delta state digest doesn't match", "errorVerbose": "delta state digest doesn't match\ngithub.com/iotexproject/iotex-core/blockchain/block.init\n\t/home/dustin/iotex-core/blockchain/block/header.go:43\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:6222\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:6199\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:233\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"}
2022-09-26T02:51:07.085Z	INFO	blockdao/blockindexer.go:107	delta state mismatch	{"ioAddr": "io1amm3fxmwna3te40fcrvwqe8he05fzeqaxhjlys", "block": 5020517}
```
when you restart the node (or docker) again, it will successfully pass this block and fullsync continues on

### Why is this needed
1. understand the root-cause why this would happen
2. need to solve this in order to set-up automatic fullsync test for testnet as well

### How important you think this is for IoTeX
- [x] must have
- [] should have
- [] nice to have

### Additional information
1. the statedb file (at height 5020516) is at: gs://blockchain-golden/arrow/trie.db
2. the chaindb file just use testnet's chaindb

**Comment by dustinxie** [comment] 2022-09-30 16:18
it also happens for at block [14546321](https://testnet.iotexscout.io/block/14546321)

**Comment by millken** [comment] 2022-10-18 09:42
I downloaded the DB and found that the height of the error is also at 12117998![tBmrPJMdau](https://user-images.githubusercontent.com/176581/196395659-76f042bd-1c0c-4ce2-b70d-c32d97d37eea.jpg)

**Comment by millken** [comment] 2022-10-19 07:28
It can work after switching to v1.8.3-rc3

**Comment by millken** [comment] 2022-10-19 10:28
After debug, the error is caused by this commit https://github.com/iotexproject/iotex-core/commit/8a3e37a9088f7f823f314646744b86090d4dde8a

**Comment by millken** [comment] 2022-10-31 00:59
Reproduce the bug in docker
`
iotex-test | 2022-10-29T04:56:17.139Z   ERROR   factory/statedb.go:336  Failed to update state. {"ioAddr": "io1t57rx9mx3kd00pfafjm5zk2vftlwxqu0w3wv67", "error": "digest in block '927e2775585daa723e8408de73073f52604ea59ce6b16baec48c4b70af23f130' vs digest in workingset '52da7f6c9d0989dfac1ca5fa9a99dceae312b3c0f28203837ccef1bfd03cddcc': delta state digest doesn't match", "errorVerbose": "delta state digest doesn't match\ngithub.com/iotexproject/iotex-core/blockchain/block.init\n\t/go/apps/iotex-core/blockchain/block/header.go:43\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:6222\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:6199\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:233\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571\ndigest in block '927e2775585daa723e8408de73073f52604ea59ce6b16baec48c4b70af23f130' vs digest in workingset '52da7f6c9d0989dfac1ca5fa9a99dceae312b3c0f28203837ccef1bfd03cddcc'\ngithub.com/iotexproject/iotex-core/state/factory.(*workingSet).ValidateBlock\n\t/go/apps/iotex-core/state/factory/workingset.go:537\ngithub.com/iotexproject/iotex-core/state/factory.(*stateDB).PutBlock\n\t/go/apps/iotex-core/state/factory/statedb.go:331\ngithub.com/iotexproject/iotex-core/blockchain/blockdao.(*BlockIndexerChecker).CheckIndexer\n\t/go/apps/iotex-core/blockchain/blockdao/blockindexer.go:95\ngithub.com/iotexproject/iotex-core/blockchain/blockdao.(*blockDAO).checkIndexers\n\t/go/apps/iotex-core/blockchain/blockdao/blockdao.go:99\ngithub.com/iotexproject/iotex-core/blockchain/blockdao.(*blockDAO).Start\n\t/go/apps/iotex-core/blockchain/blockdao/blockdao.go:93\ngithub.com/iotexproject/iotex-core/pkg/lifecycle.(*Lifecycle).OnStart.func1\n\t/go/apps/iotex-core/pkg/lifecycle/lifecycle.go:56\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.0.0-20220819030929-7fc1605a5dde/errgroup/errgroup.go:75\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"}`

**Comment by millken** [comment] 2022-11-16 10:43
trie.db start from 4070920 will also trigger this bug. If it starts from 4070921, there should be no this problem

**Comment by millken** [comment] 2022-11-23 04:55
Testnet 4070920 height has a `candidateRregister` event 
https://github.com/iotexproject/iotex-core/blob/9db224219966ea9c0bfe95a82c7e0ba71c7f2b53/action/protocol/staking/candidate_center.go#L453 , this will set operatorMap, 5020517
 height also has a `candidateRegister` event, and is the same operator, only when the map does not exist https://github.com/iotexproject/iotex-core/blob/9db224219966ea9c0bfe95a82c7e0ba71c7f2b53/action/protocol/staking/handlers.go#L652-L657 will execute the following logic, the map will be initialized after the server restarts, so if you restart at a height between 4070920 and 5020517
, the operator does not exist or will continue to execute

**Closed by millken** 2022-11-23 04:55 UTC
Labels: bug, enhancement
