### ISSUE TITLE
[ DevEnv ] Cannot restart the node image

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-core#2524] opened 2020-11-24 16:38 UTC
### What version of iotex-core are you using (`ioctl version`)?
Client:
packageVersion:"v1.0.0" packageCommitID:"e7a5c7f779687fbb6d9f69871ff827133e1a0b52" gitStatus:"clean" goVersion:"go version go1.13.5 linux/amd64" buildTime:"2020-05-14-UTC/23:13:16" 

### What operating system and processor architecture are you using?
Ubuntu 18.04

### What did you do? If possible, provide a recipe for reproducing the error.
```
cd iotex-core/tools/devenv
./setup.sh
```
after installation the node is up and running, then I stopped it:
```
./control.sh stop
```
now if I try restarting it with `./control.sh start` the container keeps restarting (see attached log)
[logs.txt](https://github.com/iotexproject/iotex-core/files/5591352/logs.txt)

**Comment by Madongming** [comment] 2020-12-21 09:08
After performing your operation, I did not reproduce the problem, but after research, I used the docker kill xxxxx && docker rm xxxxx command to delete the container, let it rebuild and start, and reproduce your problem.
Because I directly used the configuration file of config/standalone-config.yaml, the *.db file path defined in the file is the current context, not the /var/data path I expected. The undefined path bloomfilter.index.db uses the default path, which is /var/data defined in the code. This makes files other than bloomfilter.index.db lost when the container is deleted. After restarting, due to the presence of the bloomfilter.index.db file, it will cause a height error and fail to start.
This pr will fix the problem https://github.com/iotexproject/iotex-core/pull/2549

**Comment by simonerom** [comment] 2020-12-26 13:53
This is still happening to me: I pulled the latest iotex-core, then run `devenv/setup.sh -c` first and `devenv/setup.sh` to reinstall again. While it worked at first, after playing around a bit with starting/stopping the node I got again into the condition where the container doesn't start anymore, and keeps resetting indefinitely.

As soon as I delete the DB with `rm ~/iotex-var/data/bloomfilter.index.db` it can start normally again (although from height 1 of course).

**Comment by Madongming** [comment] 2020-12-27 03:34
try again pl, the pr has just been merged

**Comment by millken** [comment] 2021-02-02 01:34
step to reproduce

```
cd $IOTEX_HOME
rm -rf /data/
curl -L https://t.iotex.me/mainnet-data-latest > data.tar.gz
tar -xzf data.tar.gz

iotex-server -config-path=$IOTEX_HOME/etc/config.yaml -genesis-path=$IOTEX_HOME/etc/genesis.yaml -plugin=gateway
```

**Comment by dustinxie** [comment] 2021-02-21 07:21
fixed in https://github.com/iotexproject/iotex-core/commit/80e1bd4580634b81a862582ca9a847fef6f1d384
to be rolled out in v1.1.4 (ETA early-mid March 2021)

**Closed** 2021-03-12 17:54 UTC
Labels: bug
